// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset.sql

package database

import (
	"context"
)

const reset = `-- name: Reset :exec
TRUNCATE TABLE posts, feeds, users
RESTART IDENTITY
CASCADE
`

func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.Exec(ctx, reset)
	return err
}
